"""add password reset tokens

Revision ID: 70a355a1d4ba
Revises: 003_add_chunk_editing
Create Date: 2025-12-20 18:45:46.811838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "70a355a1d4ba"
down_revision: Union[str, Sequence[str], None] = "003_add_chunk_editing"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=512), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_reset_token_active", "password_reset_tokens", ["token", "used"], unique=False
    )
    op.create_index(
        "idx_reset_user_active", "password_reset_tokens", ["user_id", "used"], unique=False
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token"), "password_reset_tokens", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False
    )
    op.alter_column(
        "chunk_edit_history",
        "edited_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "chunk_edit_history",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "chunks",
        "is_edited",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "chunks",
        "edit_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_chunks_edited"), table_name="chunks")
    op.create_index(op.f("ix_chunks_is_edited"), "chunks", ["is_edited"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunks_is_edited"), table_name="chunks")
    op.create_index(op.f("idx_chunks_edited"), "chunks", ["is_edited", "document_id"], unique=False)
    op.alter_column(
        "chunks",
        "edit_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "chunks",
        "is_edited",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "chunk_edit_history",
        "metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'{}'::jsonb"),
        existing_nullable=False,
    )
    op.alter_column(
        "chunk_edit_history",
        "edited_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_token"), table_name="password_reset_tokens")
    op.drop_index("idx_reset_user_active", table_name="password_reset_tokens")
    op.drop_index("idx_reset_token_active", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    # ### end Alembic commands ###
